---
deployment:
  tasks:
    - export DEPLOYPATH=/home/cinqueport/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp privacy.html $DEPLOYPATH
    - /bin/cp styles.css $DEPLOYPATH
    - /bin/cp script.js $DEPLOYPATH
    - /bin/cp contact-handler.php $DEPLOYPATH
    - /bin/cp thank-you.html $DEPLOYPATH
